services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "5000:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_SENSOR_DATABASE=${MONGODB_SENSOR_DATABASE}
      - MONGODB_USER_DATABASE=${MONGODB_USER_DATABASE}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash-exp}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST:-smtp.gmail.com}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT:-587}
    depends_on:
      - mongo
      - seq

  mongo:
    image: mongo:latest 
    ports:
      - "27017:27017"  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo_data:/data/db 

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"  
      - "5342:5341" 
    environment:
      - ACCEPT_EULA=Y  

volumes:
  mongo_data: 