name: API Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - '.github/workflows/api.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - '.github/workflows/api.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Setup API Environment
      run: |
        cp .env.example .env
        sed -i 's/localhost/127.0.0.1/g' .env
        sed -i 's/mongo/127.0.0.1/g' .env
        
    - name: Restore dependencies
      run: dotnet restore api.sln
      
    - name: Build
      run: dotnet build api.sln --no-restore
      
    - name: Test
      run: dotnet test api.sln --no-build --verbosity normal 