name: Sensor Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sensor/**'
      - '.github/workflows/sensor.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'sensor/**'
      - '.github/workflows/sensor.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sensor

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Setup Sensor Config
      run: |
        cp include/config.h.example include/config.h
        sed -i 's/server address here/127.0.0.1/g' include/config.h
        sed -i 's/username here/test/g' include/config.h
        sed -i 's/pass here/test/g' include/config.h
        
    - name: Build ESP32 Project
      run: pio run
      
    - name: Run Tests
      run: pio test 